# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    cert
    sigh

    # Increment the build number (not the version number)
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "FastLaneDemoIOS.xcodeproj"
    )

    build_app
    
    run_tests(scheme: "FastLaneDemoIOS")

    skip_waiting_for_build_processing

    upload_to_testflight
    
  end

  lane :screenshots do
    capture_screenshots
    # frame_screenshots(white: true)
  end

end
