# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    cert
    sigh(force: true)
    build_app
    
    run_tests(scheme: "FastLaneDemoIOS")

    # Increment the build number (not the version number)
    # Providing the xcodeproj is optional
    increment_build_number(xcodeproj: "FastLaneDemoIOS.xcodeproj")

    # Commit the version bump
    commit_version_bump(xcodeproj: "FastLaneDemoIOS.xcodeproj")

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    add_git_tag

    # Push the new commit and tag back to your git remote
    push_to_git_remote

    upload_to_testflight

    skip_waiting_for_build_processing
  end

  lane :screenshots do
    capture_screenshots
    frame_screenshots(white: true)
    upload_to_app_store
  end

end
